"""Rule explanations are shared by the API and the interface."""
from src.config import BRUTE_FORCE_FAILURES, PORT_SCAN_UNIQUE_PORTS, SYN_FLOOD_PACKETS, SUSPICIOUS_DOMAINS

RULES = [
    {"id": "AUTH-01", "type": "Possible brute force", "severity": "High",
     "title": "Repeated authentication failures",
     "logic": f"{BRUTE_FORCE_FAILURES}+ failed logins for the same source, destination and username in an aligned 5-minute UTC bucket.",
     "why": "Repeated failures can indicate password guessing, but they can also be a misconfigured application.",
     "false_positive": "A user with an old saved password or a service using expired credentials.",
     "next_check": "Look for a successful login after the failures. Confirm the account owner and source device.",
     "limit": "Attempts split across bucket boundaries, users, or sources can evade this rule."},
    {"id": "NET-01", "type": "Port scan", "severity": "Medium",
     "title": "Multiple destination ports",
     "logic": f"{PORT_SCAN_UNIQUE_PORTS}+ distinct TCP destination ports from one source to one destination in an aligned 5-minute UTC bucket.",
     "why": "A source exploring many ports may be looking for exposed services.",
     "false_positive": "An approved vulnerability scanner or an inventory tool.",
     "next_check": "Verify the source owner and scanning schedule before escalating.",
     "limit": "Does not detect distributed, slow, horizontal or UDP scans."},
    {"id": "NET-02", "type": "Possible SYN flood", "severity": "Critical",
     "title": "Burst of SYN packets",
     "logic": f"{SYN_FLOOD_PACKETS}+ TCP SYN packets from one source to one destination port in an aligned 1-minute UTC bucket.",
     "why": "A connection-request burst may signal pressure on a service.",
     "false_positive": "A legitimate connection surge, load test or retry storm.",
     "next_check": "Check completed handshakes, service health and traffic baseline.",
     "limit": "This is a lab threshold, not proof of denial of service. No distributed-source aggregation."},
    {"id": "DNS-01", "type": "Suspicious DNS query", "severity": "High",
     "title": "DNS indicator match",
     "logic": "DNS queries are normalized to lowercase; an exact domain match triggers an alert.",
     "why": "An indicator match gives an analyst a concrete lead to investigate.",
     "false_positive": "A security test, sandbox or stale indicator.",
     "next_check": "Correlate endpoint and DNS history. These domains are fictional lab indicators.",
     "limit": "No wildcard, subdomain, reputation lookup or threat-intelligence feed.",
     "indicators": sorted(SUSPICIOUS_DOMAINS)},
    {"id": "WEB-01", "type": "Suspicious HTTP redirect", "severity": "High",
     "title": "Redirect to a lab indicator",
     "logic": "HTTP status 300-399 and an exact redirect-domain indicator match.",
     "why": "An unexpected redirect may move a browser to an untrusted destination.",
     "false_positive": "A controlled simulation or research sandbox.",
     "next_check": "Inspect proxy and browser evidence. A redirect does not prove a download or infection.",
     "limit": "No redirect-chain reconstruction, HTTPS decryption or malware analysis."},
]
